### ISSUE TITLE
Feature: User can create an account

### ISSUE THREAD

**Issue by kakriske** [kakriske/ChoreTracker#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
Users will be able to create an account or Login to an existing account.

Create an account with authentication.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can submit a username and password to access their chore list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="454" alt="Screenshot 2024-03-04 at 10 01 28 AM" src="https://github.com/kakriske/ChoreTracker/assets/142456210/b71e2a02-f075-4ce7-80ac-d73664133437">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

- [ ] #2
- [ ] Update `data.sql` to ...

### ☁️ Server Tasks

- [ ] Update `server.ts` with POST routes for user Sign-Up and Sign-In 
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to Sign-In or Sign-Up
- [ ] Create a component that directs user to User page after Sign-In/Up

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
